### ISSUE TITLE
CSS not picked up

### ISSUE THREAD

**Issue by krr** [chimeric/dokuwiki-plugin-wikicalendar#1]
Hi!

The plugin is great, but I cannot get it to pickup the CSS defined in style.css. Creating entries and viewing the calendar works perfectly, but as said, the CSS is not picked up.

**Comment by chimeric** [comment]
Try forcing a re-cache of the CSS (CTRL+SHIFT+R in Firefox) or delete the Cache.

**Comment by krr** [comment]
There is a screenshot of the calendar with the missing CSS here: http://nelumbo.dk/nocss.png

**Comment by krr** [comment]
Hey, talk about a fantastic response time -- and yes, it solved the issue. Thanks!!!

**Comment by chimeric** [comment]
You're welcome ;).

**Comment by ferdix** [comment]
I still have the same problem. I only see something like in thelink: http://nelumbo.dk/nocss.png
On plugin-page the calender looks good. Can you help to solve the problem?

**Comment by ferdix** [comment]
I could solve it by myself. It was a cache problem
