### ISSUE TITLE
Transparent pop-up

### ISSUE THREAD

**Issue by skoumal** [chimeric/dokuwiki-plugin-wikicalendar#2]
I installed wikicalendar and found here the solution for no-CSS. Now there is another problem: the pop-up with the day-page content is transparent and thus hardly readable. It should have yellow background.

**Comment by chimeric** [comment]
Which template are you using?

**Comment by skoumal** [comment]
I use monobook.

**Comment by chimeric** [comment]
Hmmm, the template doesn't provide the **highlight** style.ini CSS pattern replacement then. I'll look into it.

**Comment by skoumal** [comment]
So, it's monobook's bug, rather than wikicalendar's. I added that line with highlight to style.ini and the pop-up is yellow, now. I know that this is not the correct way, but I am happy with this.

**Comment by chimeric** [comment]
It's not really monobook's fault. **highlight** isn't part of the replacement patterns every template should offer (generally I assume most template offer it though because you usually create a new template by working on top of the default template).

**Comment by chimeric** [comment]
fixed highlighting closed by ee480a5a95015d2d462283468ae5c9807e5a60e5
