### ISSUE TITLE
Not working with 2014-05-05a "Ponder Stibbons"

### ISSUE THREAD

**Issue by Poolexxxx** [chimeric/dokuwiki-plugin-wikicalendar#22]
The calendar worked with Adora Belle, I upgraded to Ponder Stibbons and the calendar is visible, but not editable (missing the pen). Is there an easy fix?

**Comment by papillon326** [comment]
new version of dokuwiki does not contain "lib/images/edit.gif". temporary, copy the file from old version of dokuwiki.

**Comment by vit-hrachovy** [comment]
Or see #21 for possible solution

**Comment by Poolexxxx** [comment]
Just upgraded to Hrun and used ccsistvan working solution. Thank you vit-hrachovy for pointing out the solution by ccsistvan.
