### ISSUE TITLE
Not working with 2014-09-29 "Hrun"

### ISSUE THREAD

**Issue by Saalbuerger** [chimeric/dokuwiki-plugin-wikicalendar#24]
The wikicalendar isn't visible. Only a blank site is shown.

i.e.
{{cal>1:2:server:5:logbuch:}}

**Comment by skoumal** [comment]
For me, the calendar is visible, but cannot be edited.

**Comment by vit-hrachovy** [comment]
I see the same thing, calendar visible, but link to edit new page is missing. If I create the page manually, it's displayed in the calendar. It's basically issue #21

**Comment by Saalbuerger** [comment]
The Problem was the "dir" plugin.

Close
