### ISSUE TITLE
Left zero

### ISSUE THREAD

**Issue by Floriang** [chimeric/dokuwiki-plugin-wikicalendar#3]
Hi,

Pagenames with month or day ≤ 9 do not contains left zero.
It would be better if it was present, even if it is an option to enable.

Best regards.

**Comment by chrisjung-dev** [comment]
Hi Florian.
This has been done in My Fork, try this: http://github.com/campino2k/dokuwiki-plugin-wikicalendar/tree/leadingzero

**Comment by chrisjung-dev** [comment]
This has no option, there is nothing to configure and no "migration" script. No warranties :D

**Comment by Floriang** [comment]
Ok, it's a good idea, I'll watch it.
(If I may, why did you do a fork instead of sending your contributions to Chimeric?)

**Comment by chrisjung-dev** [comment]
Because sending my contribution is easier through forking...

**Comment by chimeric** [comment]
Fixed in devel

**Comment by chrisjung-dev** [comment]
\o/ I'll try that. ;)

**Comment by chimeric** [comment]
Hope it works as expected with the backwards compatibility :P.

**Comment by Floriang** [comment]
Great! I'll try that shortly! :-D
