### ISSUE TITLE
"Writing hand" character not always available

### ISSUE THREAD

**Issue by Floriang** [chimeric/dokuwiki-plugin-wikicalendar#4]
Hi,

The "writing hand" character is not always visible depending on the font present on the user's computer. When the font is not available, a square appears instead.

On the other hand, some people may find this is too small.

So, is it possible to provide an option to use an icon (already existing in DokuWiki as "lib/images/edit.gif") instead of this character?

Thank you in advance.

(I do not speak English, so my text is translated by an automatic translator.)

**Comment by Floriang** [comment]
Have you any idea?

**Comment by vojtarylko** [comment]
I think Floriang is right - this need repair

**Comment by chimeric** [comment]
use DWs own edit.gif closed by bd72d93111218885542f63bb2a4cdd831c71f1f3
