### ISSUE TITLE
Words not translatable in admin

### ISSUE THREAD

**Issue by Floriang** [chimeric/dokuwiki-plugin-wikicalendar#5]
In syntax.php, lines 216 and 246, 'Sunday' is written in clear. You should use index of the day in $langDays (or $lang['days']).
In conf/metadata.php, you should use the translation instead of english text.
In conf/default.php, you should use the index of the day.
:-)

Best regards.

**Comment by chimeric** [comment]
Why? This is just du determine the weekstart and the configuration options are english (Sunday/Monday) - I'll not localize "values" of options ;-).

**Comment by Floriang** [comment]
> Why?

Because it's better when we speak the same language. :-)
And incidentally, that makes it cleaner. ;-P

> and the configuration options are english (Sunday/Monday) - I'll not localize "values" of options

Ok, but I don't know if it was possible.

**Comment by Floriang** [comment]
In fact, it is possible without changing code of plugin but just the file "lang/fr/settings.php" :

>  $lang['weekstart'] = 'Jour de début de semaine';
> 
>  $lang['weekstart_o_Monday'] = 'Lundi'; // "Lundi" is displayed but "Monday" is returned
> 
>  $lang['weekstart_o_Sunday'] = 'Dimanche'; // "Dimanche" is displayed but "Sunday" is returned

That's all !
