### ISSUE TITLE
Feature Request: Time Offset

### ISSUE THREAD

**Issue by patchwolf** [chimeric/dokuwiki-plugin-wikicalendar#6]
I have a hosted Dokuwiki installation.  Unfortunately, I do not have control of the server upon which my Dokuwiki is installed.  Would it be possible to add a feature to define a GMT offset, so that today's date is displayed correctly?

**Comment by chimeric** [comment]
added timezone support closed by db91b7a22531ca6a6a4d96464db43612098995f9
