### ISSUE TITLE
Multilangalism

### ISSUE THREAD

**Issue by vojtarylko** [chimeric/dokuwiki-plugin-wikicalendar#7]
Hi,

I have not experience with developing plugins for dokuwiki so I cannot repair it myself. In dokuwiki-plugin-wikicalendar/conf/default.php should be somethink like

```
  $conf['weekstart'] = getLang('Monday');
```

(This also need changes in other files...)

Because with translated plugin in settings is still Monday/Sunday...

Cheers
Vojta

**Comment by chimeric** [comment]
Won't "fix" see http://github.com/chimeric/dokuwiki-plugin-wikicalendar/issues/closed#issue/5

**Comment by vojtarylko** [comment]
Oh, sorry.

**Comment by Floriang** [comment]
It's doable, see http://github.com/chimeric/dokuwiki-plugin-wikicalendar/issues/closed#issue/5/comment/313745

**Comment by chimeric** [comment]
Erm, what? Send a working patch and I think about it, I can't see how that should work... To make myself clear, I don't want people to mess with the settings.php file to change the weekstart. It should be configurable using the configuration manager.
