### ISSUE TITLE
Calendar-Form not shown if using FCGKLite

### ISSUE THREAD

**Issue by retostauss** [chimeric/dokuwiki-plugin-wikicalendar#8]
We are using FCKGLite and having problems with the calendar entry form. The content entry field is shown but not the other calendar fields.

New calendar entries may only be created if the user switchs back to "DW Edit".

**Comment by turnermm** [comment]
This is not an fckgLite issue but a CSS problem with wikicalendar.  You can test this by putting the wikicalendar css in conf/userstyles.css and then clearing out your dokuwiki and browser caches.

**Comment by retostauss** [comment]
fckgLite is working fine with wikicalendar. That problems I had are fckgLite combined with noticeboard. The issue may be closed.
